### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by sergiobaiao** [rtyle/wake-on-lan#2]
Can you write a guide on how to setup this? I created the device handler and also a virtual device for it, but when i click the "Switch" option on the virtual device nothing happens. I put my TV's MAC on the mac option, but i don't know how to activate it. Also, everytime i go to settings, the mac is not there.

**Comment by rtyle** [comment]
> I created the device handler ...

This is not a device handler.
As this project's README.md guides:

> ... deploy an instance of this **SmartApp**. The instance will need to be configured with a switch to trigger it and the target MAC address of the TV on your SmartThings hub's LAN. When the trigger switch is turned on, the SmartApp will use Wake-on-LAN to turn on the TV.
